apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-frontend
  namespace: digital-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-frontend
  template:
    metadata:
      labels:
        app: admin-frontend
    spec:
      containers:
        - name: admin-frontend
          image: savindugunasekara/digital-bank-admin-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-frontend
  namespace: digital-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-frontend
  template:
    metadata:
      labels:
        app: customer-frontend
    spec:
      containers:
        - name: customer-frontend
          image: savindugunasekara/digital-bank-customer-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
