apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: digital-bank
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: http
      port: 4001        # inside cluster
      targetPort: 4001  # container port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: digital-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: digital-banking-platform-auth-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4001
          env:
            - name: PORT
              value: "4001"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: digital-bank-secrets
                  key: JWT_SECRET
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres.digital-bank.svc.cluster.local:5432/digital_bank_auth?schema=public"
          readinessProbe:
            httpGet:
              path: /health
              port: 4001
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 4001
            initialDelaySeconds: 30
            periodSeconds: 20
