apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-service
  namespace: digital-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-service
  template:
    metadata:
      labels:
        app: fraud-service
    spec:
      containers:
        - name: fraud-service
          image: savindugunasekara/digital-bank-fraud-service:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "4004"
            - name: JWT_SECRET
              value: "supersecret_change_me"
          ports:
            - containerPort: 4004
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-service
  namespace: digital-bank
spec:
  type: ClusterIP
  selector:
    app: fraud-service
  ports:
    - name: http
      port: 4004
      targetPort: 4004
