apiVersion: v1
kind: Secret
metadata:
  name: digital-bank-secrets
  namespace: digital-bank
type: Opaque
stringData:
  # DB creds (shared by all services)
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

  # JWT secret (same across services)
  JWT_SECRET: supersecret_change_me
